name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: scalev-arc-runner
    environment:
      name: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Load secrets from 1Password
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          DOCKER_USERNAME: op://scalev/DOCKER_REGISTRY/USERNAME
          DOCKER_PASSWORD: op://scalev/DOCKER_REGISTRY/PASSWORD

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Generate version string
        run: echo "PKG_VER=${GITHUB_SHA::7}-$(date +%s)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ startsWith(github.ref, 'refs/tags/') && format('ghcr.io/{0}:{1}', github.repository, github.ref_name) || format('ghcr.io/{0}:latest', github.repository) }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PORT=${{ env.PORT }}
            PKG_VER=${{ env.PKG_VER }}

      - name: Set package visibility to public
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ORG_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f1)
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)

          PACKAGE_NAME=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')

          echo "ORG_NAME: ${ORG_NAME}"
          echo "REPO_NAME: ${REPO_NAME}"
          echo "PACKAGE_NAME: ${PACKAGE_NAME}"

          echo "Setting visibility for package: ${PACKAGE_NAME} in org: ${ORG_NAME}"

          curl -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/orgs/${ORG_NAME}/packages/container/${PACKAGE_NAME}/visibility" \
            -d '{"visibility":"public"}'

          echo "Package visibility set to public successfully!"
